# Generated by Django 4.1.7 on 2023-03-15 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_image",
            field=models.ImageField(
                default="post_pics/defaul.jpeg", upload_to="post_pics"
            ),
        ),
    ]
